[build]
  command   = "node generate-config.js"
  publish   = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "strict-origin-when-cross-origin"
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/js/firebase-config.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
